package com.restock.platform.resource.infrastructure.persistence.mongodb.repositories;

import com.restock.platform.resource.domain.model.entities.Alert;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AlertRepository extends MongoRepository<Alert, Long> {
    // Finds all alerts directed to a specific supplier (alerts generated by new orders or state changes).
    List<Alert> findAllBySupplierId(Long supplierId);

    // Finds all alerts directed to a specific restaurant (alerts about order updates).
    List<Alert> findAllByAdminRestaurantId(Long adminRestaurantId);
}
